from dotenv import load_dotenv
import os

load_dotenv()

ACCESS_TOKEN_SECRET=os.getenv('ACCESS_TOKEN_SECRET')
REFRESH_TOKEN_SECRET = os.getenv('REFRESH_TOKEN_SECRET')
REFRESH_TOKEN_EXPIRY_DAYS= int(os.getenv('REFRESH_TOKEN_EXPIRY_DAYS'))
ACCESS_TOKEN_EXPIRY_MINUTES=int(os.getenv('ACCESS_TOKEN_EXPIRY_MINUTES'))
EMAIL_VERIFICATION_TOKEN_EXPIRES_MINUTES=int(os.getenv('EMAIL_VERIFICATION_TOKEN_EXPIRES_MINUTES'))
TOKEN_BYTE_SIZE=int(os.getenv('TOKEN_BYTE_SIZE'))
ACCESS_TOKEN_VALID_TIME_MINUTES=int(os.getenv('ACCESS_TOKEN_VALID_TIME_MINUTES'))
REFRESH_EXPIRE_TIME_DAYS=int(os.getenv('REFRESH_EXPIRE_TIME_DAYS'))
DUMMY_PASSWD=os.getenv('DUMMY_PASSWD')
ALGORITHM=os.getenv('ALGORITHM')
DATABASE_URL=os.getenv('DATABASE_URL')
